name: swagstyles
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  mockito: ^5.6.4
  build_runner: ^2.15.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/swagstyles.jpg"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/images/airmax95og.jpg
    - assets/images/airmax97white.jpg
    - assets/images/airmaxtn_sunset.jpg
    - assets/images/dn_laserorange.jpg
    - assets/images/j11coolgrey.jpg
    - assets/images/j4retrofire.jpg
    - assets/images/p6000white.jpg
    - assets/images/blackleatherdn8.jpg
    - assets/images/travisaj.jpg
    - assets/images/trackledd.jpg
    - assets/images/diorb22.jpg
    - assets/images/driftblackdeeproyal.jpg
    - assets/images/womenj4.jpg
    - assets/images/shoxtriplewhite.jpg
    - assets/images/nycblackgel.jpg
    - assets/images/palacemetallic.jpg
    - assets/images/shoxblack.jpg
    - assets/images/af1white.jpg
    - assets/images/honeyblack.jpg
    - assets/images/mineralpink.jpg
    - assets/images/universityblue.jpg
    - assets/images/gammablue.jpg
    - assets/images/retrofear.jpg
    - assets/images/vapormaxplus.jpg
    - assets/images/yeezyslide.jpg
    - assets/images/j5og.jpg
    - assets/images/bapestashark.jpg
    - assets/images/forgetmenot.jpg
    - assets/images/blackcat.jpg
    - assets/images/trackwhite.jpg
    - assets/images/stormcloudasics.jpg
    - assets/images/bannerswag.jpg